// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button_blink': string;
  'button_default': string;
  'button_filled': string;
  'button_light': string;
  'sheen': string;
}
export const cssExports: CssExports;
export default cssExports;
